# Generated by Django 5.2.7 on 2026-02-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_below_market_listing_best_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
